# Generated by Django 2.2.2 on 2019-06-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='description',
        ),
    ]
