# Generated by Django 2.2.3 on 2019-07-08 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_num_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
