# Generated by Django 2.2.3 on 2019-07-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20190708_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lifecycle',
            field=models.CharField(choices=[('A', 'Active'), ('B', 'Banned'), ('D', 'Due'), ('X', 'Adjudicated')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
