# Generated by Django 2.2.2 on 2019-06-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20190614_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('CW', 'Construction waste'), ('ET', 'Electronics'), ('GLS', 'Glass'), ('HAZ', 'Hazardous'), ('FER', 'Metals'), ('HAZ', 'Hazardous'), ('MWP', 'Mixed waste products'), ('ORG', 'Organic'), ('PAC', 'Paper and cardboard'), ('MK', 'Plastics'), ('RUB', 'Rubber'), ('TOB', 'Textiles')], max_length=3),
        ),
    ]
