# Generated by Django 2.2.2 on 2019-06-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=56)),
                ('lastname', models.CharField(max_length=45)),
                ('cellphone', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=45)),
                ('post_code', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('is_mvp', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
