# Generated by Django 2.2.3 on 2019-07-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='amount',
            field=models.FloatField(default=800000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('W', 'Wining'), ('L', 'Losing')], default='W', max_length=1),
            preserve_default=False,
        ),
    ]
