# Generated by Django 2.2.3 on 2019-07-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidings', '0003_auto_20190709_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_id',
            field=models.CharField(default='ABC', max_length=50, unique=True),
        ),
    ]
