# Generated by Django 2.2.3 on 2019-07-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidings', '0004_bid_bid_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_id',
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(blank=True, choices=[('W', 'Wining'), ('L', 'Losing')], max_length=1),
        ),
    ]
