# Generated by Django 2.2.3 on 2019-07-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidings', '0005_auto_20190710_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_id',
            field=models.CharField(default='ABC', max_length=50, unique=True),
        ),
    ]
