# Generated by Django 2.2.2 on 2019-06-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.CharField(default='fsdfqdsqg', max_length=14),
        ),
    ]
