# Generated by Django 2.2.2 on 2019-06-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seller_fist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='fist_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name',
            field=models.CharField(default='james', max_length=255),
            preserve_default=False,
        ),
    ]
