# Generated by Django 2.2.2 on 2019-06-25 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cellphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cellphone',
        ),
    ]
