# Generated by Django 2.2.2 on 2019-06-30 18:59

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seller_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='email',
            field=models.EmailField(default='cool@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='first_name',
            field=models.CharField(default='man', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2019, 6, 30, 18, 59, 3, 247070, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
